DROP DATABASE IF EXISTS eBay_DB;
CREATE DATABASE eBay_DB;

USE eBay_DB;

CREATE TABLE items(
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  price INT default 0,
  PRIMARY KEY (id)
);
